### ISSUE TITLE
DataScript.R

### ISSUE THREAD

**Issue by jacobakaye** [CamSmithers/Camalytics-NBA#1]
Hi - do you have the DataScript.R code? Thanks!

**Comment by CamSmithers** [comment]
Hi, yes I have the code but it's not something I'm making available as it doesn't do much other than load the data from pre-existing excel files.

**Comment by jacobakaye** [comment]
Got it. How can I create those files?

**Comment by CamSmithers** [comment]
Unfortunately the data that I collected from the NBA isn't able to be scrapped, since the public is locked out of the api or request url. You may be able to scrape the data I got from FanDuel using Python or JavaScript; however, I didn't scrape it so I can't help you in that regard.
